gpc_indexpage_controller:
    pattern: /indexpage
    defaults: { _controller: gpc.indexpage.controller:show }
gpc_indexpage_controller2:
    pattern: /
    defaults: { _controller: gpc.indexpage.controller:show }

