gpc_main_controller:
    pattern: main
    defaults: { _controller: gpc.main.controller:show }
gpc_main_controller2:
    pattern: /
    defaults: { _controller: gpc.main.controller:show }
gpc_main_controller_disclaimer:
    pattern: /disclaimer
    defaults: { _controller: gpc.main.controller:disclaimer }
gpc_main_controller_impressum:
    pattern: /impressum
    defaults: { _controller: gpc.main.controller:impressum }
gpc_main_controller_videos:
    pattern: /videos
    defaults: { _controller: gpc.main.controller:videos }
gpc_main_controller_tutorials:
    pattern: /tutorials
    defaults: { _controller: gpc.main.controller:tutorials }
gpc_main_controller_faqs:
    pattern: /faqs
    defaults: { _controller: gpc.main.controller:faqs }

