gpc_main_controller:
    pattern: /
    defaults: { _controller: gpc.main.controller:show }
gpc_main_controller_disclaimer:
    pattern: /disclaimer
    defaults: { _controller: gpc.main.controller:disclaimer }
gpc_main_controller_impressum:
    pattern: /impressum
    defaults: { _controller: gpc.main.controller:impressum }
gpc_main_controller_videos:
    pattern: /videos
    defaults: { _controller: gpc.main.controller:videos }
gpc_main_controller_tutorial_view:
    pattern: /tutorial/view/{topic_id}
    defaults: { _controller: gpc.main.controller:tutorial_view }
gpc_main_controller_faqs:
    pattern: /faqs
    defaults: { _controller: gpc.main.controller:faqs }
gpc_main_controller_tutorials_tricks_families:
    pattern: /tutorials/tricks/familien
    defaults: { _controller: gpc.main.controller:tutorials_tricks_families }
gpc_main_controller_tutorials_search:
    pattern: /tutorials/search/{tags}/{mode}/{casesensitive}
    defaults: { _controller: gpc.main.controller:tutorials_search, tags: '', mode: 'AND', casesensitive : false }

