gpc_main_controller:
    path: /
    defaults: { _controller: gpc.main.controller:show }

gpc_main_controller_server_costs:
    path: /server_costs
    defaults: { _controller: gpc.main.controller:server_costs }

gpc_main_controller_impressum:
    path: /impressum
    defaults: { _controller: gpc.main.controller:impressum }

gpc_main_controller_videos:
    path: /videos/{page}
    defaults: { _controller: gpc.main.controller:videos, page: 1 }
    requirements:
        page: \d+

gpc_main_controller_tutorial_view:
    path: /tutorial/view/{topic_id}
    defaults: { _controller: gpc.main.controller:tutorial_view }

gpc_main_controller_faqs:
    path: /faqs
    defaults: { _controller: gpc.main.controller:faqs }

gpc_main_controller_tutorials_tricks_families:
    path: /tutorials/tricks/familien
    defaults: { _controller: gpc.main.controller:tutorials_tricks_families }

gpc_main_controller_tutorials_pens_families:
    path: /tutorials/pens/familien
    defaults: { _controller: gpc.main.controller:tutorials_pens_families }

gpc_main_controller_tutorials_search:
    path: /tutorials/search/{tags}/{mode}/{casesensitive}
    defaults: { _controller: gpc.main.controller:tutorials_search, tags: '', mode: 'AND', casesensitive : false }

