services:
    gpc.indexpage.controller:
        class: gpc\indexpage\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - @auth
            - @request
            - @dbal.conn
            - %core.php_ext%
            - %core.root_path%
            - %core.table_prefix%
            - @pagination

